apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mongo-sc
  hostPath:
    path: /data/db/mongo-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mongo-sc
  hostPath:
    path: /data/db/mongo-1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mongo-sc
  hostPath:
    path: /data/db/mongo-2
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mongo-sc
  hostPath:
    path: /data/db/mongo-3
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mongo-sc
  hostPath:
    path: /data/db/mongo-4
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
