apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: kubernetes.io/no-provisioner #Disable Dynamic Provisioning
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
