apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod02
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: size
                operator: In
                values:
                  - medium

