apiVersion: v1
kind: Pod
metadata:
  name: api-app-pod
  labels:
    type: backend
    app: banking-app
  namespace: qa
spec:
  containers:
    - name: api-app-container
      image: nginx
      ports:
        - containerPort: 3000
