apiVersion: v1
kind: Pod
metadata:
  name: db-app-pod
  labels:
    type: db
    app: banking-app
  namespace: qa
spec:
  containers:
    - name: db-app-container
      image: nginx
      ports:
        - containerPort: 2000
