apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod01
    labels:
        app: myapp
        type: frontend
spec:
    containers:
        - name: nginx-container
          image: nginx
    tolerations:
        - key: "mysize"
          operator: "Equal"
          value: "large"
          effect: "NoExecute"
          tolerationSeconds: 120
