apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod03
    labels:
        app: myapp
        type: frontend
spec:
    containers:
        - name: nginx-container
          image: nginx
    tolerations:
        - key: "mysize"
          operator: "Equal"
          value: "small"
          effect: "PreferNoSchedule"

