apiVersion: v1
kind: Pod
metadata:
  name: liveness-command-exec
spec:
  containers:
    - name: liveness-command-exec-container
      image: busybox
      command:
        - sh
        - -c
      args:
        - touch /tmp/healthy
        - |
          while true;
          do echo "$(data): Application is running successfully!!" >> /tmp/healthy;
          sleep 30;
          rm -rvf /tmp/healthy;
          done;
      livenessProbe:
        exec: 
         command:
           - cat -n /tmp/healthy
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
