apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: frontend
    namespace: qa
spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: frontend
        spec:
            containers:
                - name: nginx-container
                  image: nginx
            resources:
                requests:
                    memory: 350Mi
                    cpu: 350m
                limits:
                    memory: 550Mi
                    cpu: 550m
    replicas: 5
    strategy:
        type: RollingUpdate
    selector:
        matchExpressions:
            - key: type
              operator: In
              values: 
                - frontend
