apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-user-cluster-role
  namespace: qa
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - get 
  - delete
