apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: frontend
    namespace: prod
spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: frontend
        spec:
            containers:
                - name: nginx-container
                  image: nginx
            resources:
                requests:
                    memory: 1500M
                    cpu: 1200m
                limits:
                    memory: 2400M
                    cpu: 2400m
    replicas: 1
    strategy:
        type: RollingUpdate
    selector:
        matchExpressions:
            - key: type
              operator: In
              values: 
                - frontend
