apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limitrange
  labels:
    type: frontend
  namespace: prod
spec:
  limits:
    - default:
        memory: 2G
        cpu: 2000m
      defaultRequest:
        memory: 1G
        cpu: 1000m
      max:
        memory: 3G
        cpu: 3000m
      min:
        memory: 500M
        cpu: 500m
      type: Container
