apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limitrange
  labels:
    type: frontend
  namespace: prod
spec:
  limits:
    - default:
        memory: 2Gi
        cpu: "2"
      defaultRequest:
        memory: 1Gi
        cpu: "1"
      max:
        memory: 3Gi
        cpu: "3"
      min:
        memory: 500Mi
        cpu: 500m
      type: Container
