apiVersion: v1
kind: LimitRange
metadata:
  name: qa-limitrange
  labels:
    type: frontend
  namespace: qa
spec:
  limits:
    - default:
        memory: 500Mi
        cpu: 500m
      defaultRequest:
        memory: 300Mi
        cpu: 300m
      max:
        memory: 700Mi
        cpu: 700m
      min:
        memory: 200Mi
        cpu: 200m
      type: Container

