apiVersion: v1
kind: ResourceQuota
metadata:
    name: qa-resource-quota
    labels:
        type: frontend
    namespace: qa
spec:
    hard:
        pods: "2"
        requests.memory: "1Gi"
        requests.cpu: "1000m"
        limits.memory: "2Gi"
        limits.cpu: "2000m"
